### PR TITLE
Fix ROS_PYTHON_VERSION env hook. Fix #1

### LINKED ISSUE #1: 1.ros_python_version.sh sets wrong ROS_PYTHON_VERSION
Since we are using Python 3, the file `/opt/ros/melodic/etc/catkin/profile.d/1.ros_python_version.sh` should set `ROS_PYTHON_VERSION` to 3 instead of 2.

### PR DESCRIPTION
**Pull request by stertingen**

### CODE REVIEW

**Comment by jwhendy** [comment]
Wow, nice catch. 

@bionade24 @acxz I am surprised this didn't cause more issues already, or maybe it would/is but I haven't run into them. Here's the relevant bit that I think directs build results (so, if it's not set to `3`, it defaults to `2`:
```
### src/ros_environment-1.2.1/CMakeLists.txt

# allow overriding the Python version
if(DEFINED ENV{ROS_PYTHON_VERSION})
  set(ROS_PYTHON_VERSION "$ENV{ROS_PYTHON_VERSION}")
else()
  set(ROS_PYTHON_VERSION "2")
endif()
```
And here are associated files in `src` after building that show the effects:
```
$ grep -r ROS_PYTHON_VERSION *
src/ros_environment-1.2.1/CMakeLists.txt:if(DEFINED ENV{ROS_PYTHON_VERSION})
src/ros_environment-1.2.1/CMakeLists.txt:  set(ROS_PYTHON_VERSION "$ENV{ROS_PYTHON_VERSION}")
src/ros_environment-1.2.1/CMakeLists.txt:  set(ROS_PYTHON_VERSION "2")
src/ros_environment-1.2.1/env-hooks/1.ros_python_version.bat.in:set ROS_PYTHON_VERSION=@ROS_PYTHON_VERSION@
src/ros_environment-1.2.1/env-hooks/1.ros_python_version.sh.in:export ROS_PYTHON_VERSION=@ROS_PYTHON_VERSION@
src/build/devel/etc/catkin/profile.d/1.ros_python_version.sh:export ROS_PYTHON_VERSION=2
src/build/catkin_generated/installspace/1.ros_python_version.sh:export ROS_PYTHON_VERSION=2
src/build/atomic_configure/1.ros_python_version.sh:export ROS_PYTHON_VERSION=2
```

And one last proof that it propagates into the environment:
```
$ echo $ROS_PYTHON_VERSION
2
```

After this change/rebuild
```
$ echo $ROS_PYTHON_VERSION
3
```

I'll let the others confirm, but I see no problem merging this. Thanks!

**Comment by acxz** [comment]
Yeah this is definitely a fix we need. @stertingen can you also update the `pkgrel` and the `.SRCINFO` with this PR?

**Comment by acxz** [comment]
Thx for the contribution!

**Comment by stertingen** [comment]
So will this be available in the AUR? (https://aur.archlinux.org/packages/ros-melodic-ros-environment)

**Pull request merged**
